USE HR;

SELECT 
    *
FROM
    employee full
        JOIN
    department;

SELECT 
    EMP_HIREDATE, EMP_FNAME
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME,
    EMP_ID,
    CONCAT_WS(' ', EMP_FNAME, EMP_ID) AS 'Employee and Title'
FROM
    EMPLOYEE;

SELECT 
    EMP_HIREDATE, EMP_FNAME, DEPT_NO
FROM
    EMPLOYEE
        INNER JOIN
    DEPARTMENT ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
WHERE
    EMP_JOBTITLE = 'CLERK';

SELECT 
    CONCAT_WS(',',
            EMP_ID,
            EMP_FNAME,
            EMP_LNAME,
            EMP_AGE,
            EMP_HIREDATE,
            EMP_SALARY,
            EMP_COMMISSION,
            EMP_JOBTITLE,
            EMP_CITY,
            EMP_MANAGERID,
            EMP_MANAGERFNAME,
            EMP_MANAGERLNAME,
            EMP_MANAGAEHIREDATE,
            EMP_MANAGERSALARY,
            EMP_RESIGNDATE) AS OUTPUT
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME, EMP_SALARY
FROM
    EMPLOYEE
WHERE
    EMP_SALARY > 2000;

SELECT 
    EMP_FNAME AS NAME, EMP_HIREDATE AS STARTDATE
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME, EMP_HIREDATE
FROM
    EMPLOYEE
ORDER BY EMP_HIREDATE;

SELECT 
    EMP_FNAME, EMP_SALARY
FROM
    EMPLOYEE
ORDER BY EMP_SALARY DESC;

SELECT 
    EMP_FNAME, DEPT_NO, EMP_SALARY
FROM
    EMPLOYEE
        CROSS JOIN
    DEPARTMENT ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
WHERE
    EMP_COMMISSION IS NOT NULL
ORDER BY EMP_SALARY DESC;

SELECT 
    EMP_LNAME, EMP_JOBTITLE
FROM
    EMPLOYEE
WHERE
    EMP_MANAGERID IS NULL;

SELECT 
    EMP_FNAME, EMP_LNAME, EMP_SALARY, EMP_JOBTITLE
FROM
    EMPLOYEE
WHERE
    (EMP_JOBTITLE = 'Marketing'
        OR EMP_JOBTITLE = 'CLERK')
        AND EMP_SALARY NOT IN (2500 , 3500, 5000);

SELECT 
    MIN(EMP_SALARY) AS MIN_SALARY,
    MIN(EMP_COMMISSION) AS MIN_COMMISSION,
    MAX(EMP_SALARY) AS MAX_SALARY,
    MAX(EMP_COMMISSION) AS MAX_COMMISSION,
    AVG(EMP_SALARY) AS AVG_SALARY,
    AVG(EMP_COMMISSION) AS AVG_COMMISSION
FROM
    EMPLOYEE;

SELECT 
    DEPARTMENT.DEPT_NAME,
    SUM(EMP_SALARY) AS TOTAL_SALARY,
    SUM(EMP_COMMISSION) AS TOTAL_COMMISSION
FROM
    DEPARTMENT
        JOIN
    EMPLOYEE ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
GROUP BY DEPARTMENT.DEPT_NAME;

SELECT 
    DEPARTMENT.DEPT_NAME, COUNT(EMPLOYEE.EMP_FNAME)
FROM
    EMPLOYEE
        CROSS JOIN
    DEPARTMENT ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
GROUP BY DEPARTMENT.DEPT_NAME;

SELECT 
    DEPT_NAME, SUM(EMP_SALARY) AS TOTAL_SALARY
FROM
    EMPLOYEE
        CROSS JOIN
    DEPARTMENT ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
GROUP BY DEPARTMENT.DEPT_NAME;

SELECT 
    EMP_FNAME, EMP_COMMISSION
FROM
    EMPLOYEE
WHERE
    EMP_COMMISSION = 0;

SELECT 
    EMPLOYEE.EMP_FNAME,
    DEPARTMENT.DEPT_ID,
    CASE
        WHEN EMP_COMMISSION > 0 THEN EMP_COMMISSION
        ELSE 'NO COMMISSION'
    END AS EMP_COMMISSION
FROM
    EMPLOYEE
        LEFT JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID;
    
SELECT 
    EMP_FNAME,
    EMP_SALARY,
    CASE
        WHEN EMP_COMMISSION > 0 THEN EMP_COMMISSION * 2
        ELSE 'NO COMMISSION'
    END AS EMP_COMMISSION
FROM
    EMPLOYEE;
    
SELECT 
    SUM(EMP_SALARY), EMP_MANAGERFNAME
FROM
    EMPLOYEE
GROUP BY EMP_MANAGERFNAME;

SELECT 
    EMPLOYEE.EMP_MANAGERFNAME,
    COUNT(EMPLOYEE.EMP_FNAME),
    DEPARTMENT.DEPT_NAME
FROM
    DEPARTMENT
        JOIN
    EMPLOYEE ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
GROUP BY DEPARTMENT.DEPT_NAME;

SELECT 
    EMPLOYEE.EMP_FNAME,
    DEPARTMENT.DEPT_ID,
    EMPLOYEE.EMP_SALARY,
    EMPLOYEE.EMP_MANAGERFNAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
WHERE
    EMPLOYEE.EMP_MANAGERFNAME LIKE '_a%'
        AND EMPLOYEE.EMP_LNAME LIKE '_A%';

SELECT 
    MAX(EMP_SALARY), DEPT_NAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON DEPARTMENT.DEPT_ID = EMPLOYEE.EMP_ID
GROUP BY DEPT_NAME;

SELECT 
    EMP_FNAME,
    EMP_SALARY,
    CASE
        WHEN EMP_COMMISSION > 0 THEN EMP_SALARY * 0.1
        ELSE '1'
    END AS EMP_COMMISSION
FROM
    EMPLOYEE;
    
SELECT 
    SUBSTRING(EMP_LNAME, 2, 4) AS STRINGG
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME,
    EMP_LNAME,
    CONCAT_WS('-', EMP_FNAME, EMP_LNAME) AS FULLNAME,
    DATE_FORMAT(EMP_HIREDATE, '%M') AS HIRE_MONTH
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME,
    EMP_SALARY,
    CASE
        WHEN EMP_SALARY / 2 > 10000 THEN EMP_SALARY * 0.1
        ELSE EMP_SALARY * 0.11 + 1500
    END AS YEARLY_INCERMENT
FROM
    EMPLOYEE;
    
SELECT 
    CONCAT(SUBSTRING(EMP_ID, 1, 2),
            '00',
            SUBSTRING(EMP_ID, 4),
            'E') AS new_EMPID,
    UPPER(EMP_SALARY) AS NEW_SALARY,
    REPLACE(UPPER(EMP_MANAGERFNAME),
        'Z',
        '$') AS NEW_MANAGERFNAME
FROM
    (SELECT 
        EMP_ID, EMP_SALARY, EMP_MANAGERFNAME
    FROM
        employee
    WHERE
        EMP_MANAGERID IS NOT NULL) AS NEW_DATA;

SELECT 
    CONCAT(UPPER(SUBSTRING(EMP_LNAME, 1, 1)),
            LOWER(SUBSTRING(EMP_LNAME, 2))) AS NEW_NAME,
    LENGTH(EMP_LNAME) AS LNAME_LENGTH
FROM
    EMPLOYEE
WHERE
    EMP_LNAME LIKE 'J%'
        OR EMP_LNAME LIKE 'A%'
        OR EMP_LNAME LIKE 'M%'
ORDER BY EMP_LNAME;

SELECT 
    EMP_LNAME,
    CONCAT('$',
            LPAD(FORMAT(EMP_SALARY, 0), 15, '$')) AS SALARY
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME
FROM
    EMPLOYEE
WHERE
    EMP_FNAME = REVERSE(EMP_FNAME);

SELECT 
    CONCAT(UPPER(SUBSTRING(EMP_FNAME, 1, 1))) AS INITIAL,
    LOWER(SUBSTRING(EMP_FNAME, 2)) AS INITCAPS_NAME
FROM
    EMPLOYEE;

SELECT 
    CONCAT(LOWER(SUBSTRING(EMP_FNAME, 1, 1))) AS INTIAL,
    CONCAT((EMP_FNAME), '@systechusa.com') AS EMAIL_ID,
    EMP_FNAME
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME, EMP_JOBTITLE
FROM
    EMPLOYEE
WHERE
    EMP_JOBTITLE = 'Marketing';

SELECT 
    EMPLOYEE.EMP_FNAME, DEPARTMENT.DEPT_NAME, EMPLOYEE.EMP_CITY
FROM
    EMPLOYEE
        LEFT JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    EMPLOYEE.EMP_CITY = 'AHMEDABAD';

SELECT 
    EMP_FNAME, EMP_SALARY
FROM
    EMPLOYEE
WHERE
    EMP_SALARY = (SELECT 
            MIN(EMP_SALARY)
        FROM
            EMPLOYEE);

SELECT 
    EMP_FNAME, EMP_SALARY
FROM
    EMPLOYEE
WHERE
    NOT EMP_SALARY = (SELECT 
            MIN(EMP_SALARY)
        FROM
            EMPLOYEE);
            
SELECT 
    EMP_LNAME, DEPT_NO, DEPT_NAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
GROUP BY DEPT_NO;

SELECT 
    EMP_JOBTITLE, DEPT_NO
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    DEPT_NO = 4;
    
SELECT 
    EMPLOYEE.EMP_LNAME,
    DEPARTMENT.DEPT_NAME,
    EMPLOYEE.EMP_CITY,
    EMPLOYEE.EMP_COMMISSION
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    EMP_COMMISSION IS NOT NULL;

SELECT 
    EMPLOYEE.EMP_LNAME, DEPARTMENT.DEPT_NAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    EMP_LNAME LIKE '%A';

SELECT 
    EMP_LNAME, EMP_JOBTITLE, EMP_CITY, DEPT_NO
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    EMP_CITY = 'SURAT';

SELECT 
    EMP_LNAME, EMP_ID, EMP_MANAGERFNAME, EMP_MANAGERID
FROM
    EMPLOYEE
WHERE
    EMP_MANAGERID IS NOT NULL;

SELECT 
    EMP_LNAME, EMP_ID, EMP_MANAGERFNAME, EMP_MANAGERID
FROM
    EMPLOYEE;

SELECT 
    EMP_LNAME, DEPT_NO, DEPT_NAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
GROUP BY DEPT_NO;

SELECT 
    EMP_FNAME,
    EMP_JOBTITLE,
    DEPT_NAME,
    EMP_SALARY,
    CASE
        WHEN EMP_SALARY >= 50000 THEN 'A'
        WHEN EMP_SALARY >= 30000 THEN 'B'
        WHEN EMP_SALARY < 30000 THEN 'C'
        ELSE 'NA'
    END AS 'GRADE'
FROM
    EMPLOYEE
        LEFT JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID;

SELECT 
    EMP_FNAME AS EMPLOYEE_NAME,
    EMP_HIREDATE AS emp_hire_date,
    EMP_MANAGERFNAME AS manager_name,
    EMP_MANAGAEHIREDATE AS man_hire_date
FROM
    EMPLOYEE
WHERE
    EMP_HIREDATE < EMP_MANAGAEHIREDATE;

SELECT 
    EMP_FNAME, EMP_LNAME, EMP_HIREDATE
FROM
    EMPLOYEE
WHERE
    EMP_JOBTITLE = 'Marketing';
    
SELECT 
    EMP_ID, EMP_FNAME, EMP_LNAME, EMP_SALARY
FROM
    EMPLOYEE
WHERE
    EMP_SALARY > (SELECT 
            AVG(EMP_SALARY)
        FROM
            EMPLOYEE)
ORDER BY EMP_SALARY;
SELECT 
    AVG(EMP_SALYAR)
FROM
    EMPLOYEE;

SELECT 
    EMP_FNAME, EMP_LNAME, DEPT_EMPFNAME, DEPT_LNAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    DEPT_LNAME LIKE '%U';

SELECT 
    EMP_LNAME, DEPT_NO, DEPT_LOCATION, EMP_ID
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    DEPT_LOCATION = 'ATLANTA';

SELECT 
    EMP_FNAME, EMP_SALARY
FROM
    EMPLOYEE
WHERE
    EMP_MANAGERLNAME = 'fillmore';

SELECT 
    EMP_LNAME, DEPT_NO, EMP_ID, DEPT_NAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    DEPT_NAME = 'OPREATIONS';

SELECT 
    EMP_ID, EMP_FNAME, EMP_SALARY, DEPT_EMPFNAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
WHERE
    EMP_SALARY > (SELECT 
            AVG(EMP_SALARY)
        FROM
            EMPLOYEE)
        AND DEPT_EMPFNAME LIKE '%U';
        
SELECT 
    EMP_FNAME, EMP_JOBTITLE
FROM
    EMPLOYEE
WHERE
    EMP_JOBTITLE = 'Marketing';

SELECT 
    EMP_FNAME,
    EMP_SALARY,
    DEPT_NO,
    DEPT_NAME,
    CASE
        WHEN DEPT_NO IN (1 , 3) THEN '%5'
        WHEN DEPT_NO = 2 THEN '%10'
        WHEN DEPT_NO IN (4 , 5) THEN '%15'
        ELSE 'NA'
    END AS RAISE_SALARY
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID;

SELECT 
    EMP_FNAME, EMP_SALARY
FROM
    EMPLOYEE
ORDER BY EMP_SALARY DESC
LIMIT 3;

SELECT 
    EMP_FNAME, EMP_SALARY, EMP_COMMISSION
FROM
    EMPLOYEE;

SELECT 
    EMP_MANAGERFNAME, EMP_MANAGERSALARY, DEPT_NAME
FROM
    EMPLOYEE
        JOIN
    DEPARTMENT ON EMPLOYEE.EMP_ID = DEPARTMENT.DEPT_ID
ORDER BY EMP_MANAGERSALARY DESC
LIMIT 3;

SELECT 
    EMP_MANAGERFNAME,
    EMP_MANAGAEHIREDATE,
    EMP_RESIGNDATE,
    DATEDIFF(EMP_MANAGAEHIREDATE, EMP_RESIGNDATE) AS DATEDIFFFINDAYS,
    CONCAT(FLOOR(DATEDIFF(EMP_MANAGAEHIREDATE, EMP_RESIGNDATE) / 365), " ", 'YEAR',
    FLOOR((DATEDIFF(EMP_MANAGAEHIREDATE, EMP_RESIGNDATE) % 365)/ 30), 'MONTHS',
    DATEDIFF(EMP_MANAGAEHIREDATE, EMP_RESIGNDATE) % 30 , " ", 'DAYS') AS DATEFROMAT
    FROM EMPLOYEE;
    
    
    